<?php

return array (
  'aka' => 
  array (
    0 => 'fat',
    1 => 'twi',
  ),
  'ara' => 
  array (
    0 => 'aao',
    1 => 'abh',
    2 => 'abv',
    3 => 'acm',
    4 => 'acq',
    5 => 'acw',
    6 => 'acx',
    7 => 'acy',
    8 => 'adf',
    9 => 'aeb',
    10 => 'aec',
    11 => 'afb',
    12 => 'ajp',
    13 => 'apc',
    14 => 'apd',
    15 => 'arb',
    16 => 'arq',
    17 => 'ars',
    18 => 'ary',
    19 => 'arz',
    20 => 'auz',
    21 => 'avl',
    22 => 'ayh',
    23 => 'ayl',
    24 => 'ayn',
    25 => 'ayp',
    26 => 'pga',
    27 => 'shu',
    28 => 'ssh',
    29 => 'bbz',
  ),
  'aym' => 
  array (
    0 => 'ayc',
    1 => 'ayr',
  ),
  'aze' => 
  array (
    0 => 'azb',
    1 => 'azj',
  ),
  'bal' => 
  array (
    0 => 'bcc',
    1 => 'bgn',
    2 => 'bgp',
  ),
  'bik' => 
  array (
    0 => 'bcl',
    1 => 'bln',
    2 => 'bto',
    3 => 'cts',
    4 => 'fbl',
    5 => 'lbl',
    6 => 'rbl',
    7 => 'ubl',
    8 => 'bhk',
  ),
  'bnc' => 
  array (
    0 => 'ebk',
    1 => 'lbk',
    2 => 'obk',
    3 => 'rbk',
    4 => 'vbk',
  ),
  'bua' => 
  array (
    0 => 'bxm',
    1 => 'bxr',
    2 => 'bxu',
  ),
  'chm' => 
  array (
    0 => 'mhr',
    1 => 'mrj',
  ),
  'cre' => 
  array (
    0 => 'crj',
    1 => 'crk',
    2 => 'crl',
    3 => 'crm',
    4 => 'csw',
    5 => 'cwd',
    6 => 'nsk',
    7 => 'moe',
    8 => 'atj',
    9 => 'crg',
    10 => 'ojs',
    11 => 'ojw',
  ),
  'del' => 
  array (
    0 => 'umu',
    1 => 'unm',
  ),
  'den' => 
  array (
    0 => 'scs',
    1 => 'xsl',
  ),
  'din' => 
  array (
    0 => 'dib',
    1 => 'dik',
    2 => 'dip',
    3 => 'diw',
    4 => 'dks',
  ),
  'doi' => 
  array (
    0 => 'dgo',
    1 => 'xnr',
  ),
  'est' => 
  array (
    0 => 'ekk',
    1 => 'vro',
  ),
  'fas' => 
  array (
    0 => 'pes',
    1 => 'prs',
  ),
  'ful' => 
  array (
    0 => 'ffm',
    1 => 'fub',
    2 => 'fuc',
    3 => 'fue',
    4 => 'fuf',
    5 => 'fuh',
    6 => 'fui',
    7 => 'fuq',
    8 => 'fuv',
  ),
  'gba' => 
  array (
    0 => 'bdt',
    1 => 'gbp',
    2 => 'gbq',
    3 => 'gmm',
    4 => 'gso',
    5 => 'gya',
    6 => 'mdo',
  ),
  'gon' => 
  array (
    0 => 'esg',
    1 => 'gno',
    2 => 'wsg',
    3 => 'ggo',
  ),
  'grb' => 
  array (
    0 => 'gbo',
    1 => 'gec',
    2 => 'grj',
    3 => 'grv',
    4 => 'gry',
  ),
  'grn' => 
  array (
    0 => 'gnw',
    1 => 'gug',
    2 => 'gui',
    3 => 'gun',
    4 => 'nhd',
  ),
  'hai' => 
  array (
    0 => 'hax',
    1 => 'hdn',
  ),
  'hbs' => 
  array (
    0 => 'bos',
    1 => 'cnr',
    2 => 'hrv',
    3 => 'srp',
  ),
  'hmn' => 
  array (
    0 => 'cqd',
    1 => 'hea',
    2 => 'hma',
    3 => 'hmc',
    4 => 'hmd',
    5 => 'hme',
    6 => 'hmg',
    7 => 'hmh',
    8 => 'hmi',
    9 => 'hmj',
    10 => 'hml',
    11 => 'hmm',
    12 => 'hmp',
    13 => 'hmq',
    14 => 'hms',
    15 => 'hmw',
    16 => 'hmy',
    17 => 'hmz',
    18 => 'hnj',
    19 => 'hrm',
    20 => 'huj',
    21 => 'mmr',
    22 => 'muq',
    23 => 'mww',
    24 => 'sfm',
    25 => 'blu',
  ),
  'iku' => 
  array (
    0 => 'ike',
    1 => 'ikt',
  ),
  'ipk' => 
  array (
    0 => 'esi',
    1 => 'esk',
  ),
  'jrb' => 
  array (
    0 => 'aju',
    1 => 'jye',
    2 => 'yhd',
    3 => 'yud',
    4 => 'ajt',
  ),
  'kau' => 
  array (
    0 => 'kby',
    1 => 'knc',
    2 => 'krt',
    3 => 'bms',
    4 => 'kbl',
  ),
  'kln' => 
  array (
    0 => 'enb',
    1 => 'eyo',
    2 => 'niq',
    3 => 'oki',
    4 => 'pko',
    5 => 'sgc',
    6 => 'spy',
    7 => 'tec',
    8 => 'tuy',
  ),
  'kok' => 
  array (
    0 => 'gom',
    1 => 'knn',
  ),
  'kom' => 
  array (
    0 => 'koi',
    1 => 'kpv',
  ),
  'kon' => 
  array (
    0 => 'kng',
    1 => 'kwy',
    2 => 'ldi',
  ),
  'kpe' => 
  array (
    0 => 'gkp',
    1 => 'xpe',
  ),
  'kur' => 
  array (
    0 => 'ckb',
    1 => 'kmr',
    2 => 'sdh',
  ),
  'lah' => 
  array (
    0 => 'hnd',
    1 => 'hno',
    2 => 'jat',
    3 => 'phr',
    4 => 'pnb',
    5 => 'skr',
    6 => 'xhe',
    7 => 'pmu',
  ),
  'lav' => 
  array (
    0 => 'ltg',
    1 => 'lvs',
  ),
  'luy' => 
  array (
    0 => 'bxk',
    1 => 'ida',
    2 => 'lkb',
    3 => 'lko',
    4 => 'lks',
    5 => 'lri',
    6 => 'lrm',
    7 => 'lsm',
    8 => 'lto',
    9 => 'lts',
    10 => 'lwg',
    11 => 'nle',
    12 => 'nyd',
    13 => 'rag',
  ),
  'man' => 
  array (
    0 => 'emk',
    1 => 'mku',
    2 => 'mlq',
    3 => 'mnk',
    4 => 'msc',
    5 => 'mwk',
    6 => 'myq',
  ),
  'mlg' => 
  array (
    0 => 'bhr',
    1 => 'bmm',
    2 => 'bzc',
    3 => 'msh',
    4 => 'plt',
    5 => 'skg',
    6 => 'tdx',
    7 => 'tkg',
    8 => 'txy',
    9 => 'xmv',
    10 => 'xmw',
    11 => 'bjq',
  ),
  'msa' => 
  array (
    0 => 'khk',
    1 => 'mvf',
    2 => 'bjn',
    3 => 'btj',
    4 => 'bve',
    5 => 'bvu',
    6 => 'coa',
    7 => 'dup',
    8 => 'hji',
    9 => 'ind',
    10 => 'jak',
    11 => 'jax',
    12 => 'kvb',
    13 => 'kvr',
    14 => 'kxd',
    15 => 'lce',
    16 => 'lcf',
    17 => 'liw',
    18 => 'max',
    19 => 'meo',
    20 => 'mfa',
    21 => 'mfb',
    22 => 'min',
    23 => 'mqg',
    24 => 'msi',
    25 => 'mui',
    26 => 'orn',
    27 => 'ors',
    28 => 'pel',
    29 => 'pse',
    30 => 'tmw',
    31 => 'urk',
    32 => 'vkk',
    33 => 'vkt',
    34 => 'xmm',
    35 => 'zlm',
    36 => 'zmi',
    37 => 'zsm',
    38 => 'mly',
    39 => 'omy',
  ),
  'mwr' => 
  array (
    0 => 'dhd',
    1 => 'mtr',
    2 => 'mve',
    3 => 'rwr',
    4 => 'swv',
    5 => 'wry',
  ),
  'nep' => 
  array (
    0 => 'dty',
    1 => 'npi',
  ),
  'nor' => 
  array (
    0 => 'nno',
    1 => 'nob',
  ),
  'oji' => 
  array (
    0 => 'ciw',
    1 => 'ojb',
    2 => 'ojc',
    3 => 'ojg',
    4 => 'ojs',
    5 => 'ojw',
    6 => 'otw',
    7 => 'alq',
    8 => 'pot',
    9 => 'crg',
  ),
  'ori' => 
  array (
    0 => 'ory',
    1 => 'spv',
  ),
  'orm' => 
  array (
    0 => 'gax',
    1 => 'gaz',
    2 => 'hae',
    3 => 'orc',
  ),
  'pus' => 
  array (
    0 => 'pbt',
    1 => 'pbu',
    2 => 'pst',
  ),
  'que' => 
  array (
    0 => 'qub',
    1 => 'qud',
    2 => 'quf',
    3 => 'qug',
    4 => 'quh',
    5 => 'quk',
    6 => 'qul',
    7 => 'qup',
    8 => 'qur',
    9 => 'qus',
    10 => 'quw',
    11 => 'qux',
    12 => 'quy',
    13 => 'quz',
    14 => 'qva',
    15 => 'qvc',
    16 => 'qve',
    17 => 'qvh',
    18 => 'qvi',
    19 => 'qvj',
    20 => 'qvl',
    21 => 'qvm',
    22 => 'qvn',
    23 => 'qvo',
    24 => 'qvp',
    25 => 'qvs',
    26 => 'qvw',
    27 => 'qvz',
    28 => 'qwa',
    29 => 'qwc',
    30 => 'qwh',
    31 => 'qws',
    32 => 'qxa',
    33 => 'qxc',
    34 => 'qxh',
    35 => 'qxl',
    36 => 'qxn',
    37 => 'qxo',
    38 => 'qxp',
    39 => 'qxr',
    40 => 'qxt',
    41 => 'qxu',
    42 => 'qxw',
    43 => 'cqu',
  ),
  'raj' => 
  array (
    0 => 'bgq',
    1 => 'gda',
    2 => 'gju',
    3 => 'hoj',
    4 => 'mup',
    5 => 'wbr',
  ),
  'rom' => 
  array (
    0 => 'rmc',
    1 => 'rmf',
    2 => 'rml',
    3 => 'rmn',
    4 => 'rmo',
    5 => 'rmw',
    6 => 'rmy',
    7 => 'emx',
    8 => 'rge',
    9 => 'rmd',
    10 => 'rme',
    11 => 'rmg',
    12 => 'rmi',
    13 => 'rmr',
    14 => 'rmu',
    15 => 'rsb',
  ),
  'sqi' => 
  array (
    0 => 'aae',
    1 => 'aat',
    2 => 'aln',
    3 => 'als',
  ),
  'srd' => 
  array (
    0 => 'sdc',
    1 => 'sdn',
    2 => 'src',
    3 => 'sro',
  ),
  'swa' => 
  array (
    0 => 'swc',
    1 => 'swh',
  ),
  'syr' => 
  array (
    0 => 'aii',
    1 => 'cld',
  ),
  'tmh' => 
  array (
    0 => 'taq',
    1 => 'thv',
    2 => 'thz',
    3 => 'ttq',
  ),
  'uzb' => 
  array (
    0 => 'uzn',
    1 => 'uzs',
  ),
  'yid' => 
  array (
    0 => 'ydd',
    1 => 'yih',
  ),
  'zap' => 
  array (
    0 => 'zaa',
    1 => 'zab',
    2 => 'zac',
    3 => 'zad',
    4 => 'zae',
    5 => 'zaf',
    6 => 'zai',
    7 => 'zam',
    8 => 'zao',
    9 => 'zaq',
    10 => 'zar',
    11 => 'zas',
    12 => 'zat',
    13 => 'zav',
    14 => 'zaw',
    15 => 'zax',
    16 => 'zca',
    17 => 'zcd',
    18 => 'zoo',
    19 => 'zpa',
    20 => 'zpb',
    21 => 'zpc',
    22 => 'zpd',
    23 => 'zpe',
    24 => 'zpf',
    25 => 'zpg',
    26 => 'zph',
    27 => 'zpi',
    28 => 'zpj',
    29 => 'zpk',
    30 => 'zpl',
    31 => 'zpm',
    32 => 'zpn',
    33 => 'zpo',
    34 => 'zpp',
    35 => 'zpq',
    36 => 'zpr',
    37 => 'zps',
    38 => 'zpt',
    39 => 'zpu',
    40 => 'zpv',
    41 => 'zpw',
    42 => 'zpx',
    43 => 'zpy',
    44 => 'zpz',
    45 => 'zsr',
    46 => 'zte',
    47 => 'ztg',
    48 => 'ztl',
    49 => 'ztm',
    50 => 'ztn',
    51 => 'ztp',
    52 => 'ztq',
    53 => 'zts',
    54 => 'ztt',
    55 => 'ztu',
    56 => 'ztx',
    57 => 'zty',
    58 => 'ztc',
    59 => 'xzp',
  ),
  'zha' => 
  array (
    0 => 'zch',
    1 => 'zeh',
    2 => 'zgb',
    3 => 'zgm',
    4 => 'zgn',
    5 => 'zhd',
    6 => 'zhn',
    7 => 'zlj',
    8 => 'zln',
    9 => 'zlq',
    10 => 'zqe',
    11 => 'zyb',
    12 => 'zyg',
    13 => 'zyj',
    14 => 'zyn',
    15 => 'zzj',
    16 => 'ccx',
    17 => 'ccy',
  ),
  'zho' => 
  array (
    0 => 'cdo',
    1 => 'cjy',
    2 => 'cmn',
    3 => 'cnp',
    4 => 'cpx',
    5 => 'csp',
    6 => 'czh',
    7 => 'czo',
    8 => 'gan',
    9 => 'hak',
    10 => 'hsn',
    11 => 'lzh',
    12 => 'mnp',
    13 => 'nan',
    14 => 'wuu',
    15 => 'yue',
  ),
  'zza' => 
  array (
    0 => 'diq',
    1 => 'kiu',
  ),
  'mon' => 
  array (
    0 => 'khk',
    1 => 'mvf',
  ),
);