<?php

return array (
  'ab' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ab',
    'iso_639_1_name' => 'Abkhazian',
    'iso_639_1_native' => 'аҧсуа бызшәа, аҧсшәа',
    'iso_639_1_notes' => 'Abkhaz',
    'iso_639_2_t_code' => 'abk',
    'iso_639_2_b_code' => 'abk',
    'iso_639_3_code' => 'abk',
    'iso_639_5_code' => 'ccn',
    'iso_639_5_name' => 'Northwest Caucasian',
    'iso_639_6_code' => 'abks',
  ),
  'aa' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'aa',
    'iso_639_1_name' => 'Afar',
    'iso_639_1_native' => 'Afaraf',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'aar',
    'iso_639_2_b_code' => 'aar',
    'iso_639_3_code' => 'aar',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => 'aars',
  ),
  'af' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'af',
    'iso_639_1_name' => 'Afrikaans',
    'iso_639_1_native' => 'Afrikaans',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'afr',
    'iso_639_2_b_code' => 'afr',
    'iso_639_3_code' => 'afr',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'afrs',
  ),
  'ak' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ak',
    'iso_639_1_name' => 'Akan',
    'iso_639_1_native' => 'Akan',
    'iso_639_1_notes' => 'Twi is tw/twi, Fanti is fat',
    'iso_639_2_t_code' => 'aka',
    'iso_639_2_b_code' => 'aka',
    'iso_639_3_code' => 'aka',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'sq' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'sq',
    'iso_639_1_name' => 'Albanian',
    'iso_639_1_native' => NULL,
    'iso_639_1_notes' => 'Called "Albanian Phylozone" in 639-6',
    'iso_639_2_t_code' => 'sqi',
    'iso_639_2_b_code' => 'alb',
    'iso_639_3_code' => 'sqi',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => NULL,
    'iso_639_6_code' => NULL,
  ),
  'am' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'am',
    'iso_639_1_name' => 'Amharic',
    'iso_639_1_native' => 'አማርኛ',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'amh',
    'iso_639_2_b_code' => 'amh',
    'iso_639_3_code' => 'amh',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => NULL,
  ),
  'ar' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ar',
    'iso_639_1_name' => 'Arabic',
    'iso_639_1_native' => 'العربية',
    'iso_639_1_notes' => 'Standard Arabic is arb',
    'iso_639_2_t_code' => 'ara',
    'iso_639_2_b_code' => 'ara',
    'iso_639_3_code' => 'ara',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => NULL,
  ),
  'an' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'an',
    'iso_639_1_name' => 'Aragonese',
    'iso_639_1_native' => 'aragonés',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'arg',
    'iso_639_2_b_code' => 'arg',
    'iso_639_3_code' => 'arg',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'hy' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'hy',
    'iso_639_1_name' => 'Armenian',
    'iso_639_1_native' => 'Հայերեն',
    'iso_639_1_notes' => 'ISO 639-3 code hye is for Eastern Armenian, hyw is for Western Armenian, and xcl is for Classical Armenian',
    'iso_639_2_t_code' => 'hye',
    'iso_639_2_b_code' => 'arm',
    'iso_639_3_code' => 'hye',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'as' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'as',
    'iso_639_1_name' => 'Assamese',
    'iso_639_1_native' => 'অসমীয়া',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'asm',
    'iso_639_2_b_code' => 'asm',
    'iso_639_3_code' => 'asm',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'av' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'av',
    'iso_639_1_name' => 'Avaric',
    'iso_639_1_native' => 'авар мацӀ, магӀарул мацӀ',
    'iso_639_1_notes' => 'Also known as Avar',
    'iso_639_2_t_code' => 'ava',
    'iso_639_2_b_code' => 'ava',
    'iso_639_3_code' => 'ava',
    'iso_639_5_code' => 'ccn',
    'iso_639_5_name' => 'Northeast Caucasian',
    'iso_639_6_code' => NULL,
  ),
  'ae' => 
  array (
    'macrolanguage' => false,
    'ancient' => true,
    'iso_639_1_code' => 'ae',
    'iso_639_1_name' => 'Avestan',
    'iso_639_1_native' => 'avesta',
    'iso_639_1_notes' => 'ancient',
    'iso_639_2_t_code' => 'ave',
    'iso_639_2_b_code' => 'ave',
    'iso_639_3_code' => 'ave',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ay' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ay',
    'iso_639_1_name' => 'Aymara',
    'iso_639_1_native' => 'aymar aru',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'aym',
    'iso_639_2_b_code' => 'aym',
    'iso_639_3_code' => 'aym',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Aymaran',
    'iso_639_6_code' => NULL,
  ),
  'az' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'az',
    'iso_639_1_name' => 'Azerbaijani',
    'iso_639_1_native' => 'azərbaycan dili',
    'iso_639_1_notes' => 'Also known as Azeri',
    'iso_639_2_t_code' => 'aze',
    'iso_639_2_b_code' => 'aze',
    'iso_639_3_code' => 'aze',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'bm' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'bm',
    'iso_639_1_name' => 'Bambara',
    'iso_639_1_native' => 'bamanankan',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'bam',
    'iso_639_2_b_code' => 'bam',
    'iso_639_3_code' => 'bam',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ba' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ba',
    'iso_639_1_name' => 'Bashkir',
    'iso_639_1_native' => 'башҡорт теле',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'bak',
    'iso_639_2_b_code' => 'bak',
    'iso_639_3_code' => 'bak',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'eu' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'eu',
    'iso_639_1_name' => 'Basque',
    'iso_639_1_native' => 'euskara, euskera',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'eus',
    'iso_639_2_b_code' => 'baq',
    'iso_639_3_code' => 'eus',
    'iso_639_5_code' => 'euq',
    'iso_639_5_name' => 'Language isolate',
    'iso_639_6_code' => NULL,
  ),
  'be' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'be',
    'iso_639_1_name' => 'Belarusian',
    'iso_639_1_native' => 'беларуская мова',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'bel',
    'iso_639_2_b_code' => 'bel',
    'iso_639_3_code' => 'bel',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'bn' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'bn',
    'iso_639_1_name' => 'Bengali',
    'iso_639_1_native' => 'বাংলা',
    'iso_639_1_notes' => 'Also known as Bangla',
    'iso_639_2_t_code' => 'ben',
    'iso_639_2_b_code' => 'ben',
    'iso_639_3_code' => 'ben',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'bi' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'bi',
    'iso_639_1_name' => 'Bislama',
    'iso_639_1_native' => 'Bislama',
    'iso_639_1_notes' => 'Language formed from English and Vanuatuan languages, with some French influence.',
    'iso_639_2_t_code' => 'bis',
    'iso_639_2_b_code' => 'bis',
    'iso_639_3_code' => 'bis',
    'iso_639_5_code' => 'crp',
    'iso_639_5_name' => 'Creole',
    'iso_639_6_code' => NULL,
  ),
  'bs' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'bs',
    'iso_639_1_name' => 'Bosnian',
    'iso_639_1_native' => 'bosanski jezik',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'bos',
    'iso_639_2_b_code' => 'bos',
    'iso_639_3_code' => 'bos',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'boss',
  ),
  'br' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'br',
    'iso_639_1_name' => 'Breton',
    'iso_639_1_native' => 'brezhoneg',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'bre',
    'iso_639_2_b_code' => 'bre',
    'iso_639_3_code' => 'bre',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'bg' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'bg',
    'iso_639_1_name' => 'Bulgarian',
    'iso_639_1_native' => 'български език',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'bul',
    'iso_639_2_b_code' => 'bul',
    'iso_639_3_code' => 'bul',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'buls',
  ),
  'my' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'my',
    'iso_639_1_name' => 'Burmese',
    'iso_639_1_native' => 'ဗမာစာ',
    'iso_639_1_notes' => 'Also known as Myanmar',
    'iso_639_2_t_code' => 'mya',
    'iso_639_2_b_code' => 'bur',
    'iso_639_3_code' => 'mya',
    'iso_639_5_code' => 'sit',
    'iso_639_5_name' => 'Sino-Tibetan',
    'iso_639_6_code' => NULL,
  ),
  'ca' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ca',
    'iso_639_1_name' => 'Catalan, Valencian',
    'iso_639_1_native' => 'català',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'cat',
    'iso_639_2_b_code' => 'cat',
    'iso_639_3_code' => 'cat',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ch' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ch',
    'iso_639_1_name' => 'Chamorro',
    'iso_639_1_native' => 'Chamoru',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'cha',
    'iso_639_2_b_code' => 'cha',
    'iso_639_3_code' => 'cha',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'ce' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ce',
    'iso_639_1_name' => 'Chechen',
    'iso_639_1_native' => 'нохчийн мотт',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'che',
    'iso_639_2_b_code' => 'che',
    'iso_639_3_code' => 'che',
    'iso_639_5_code' => 'ccn',
    'iso_639_5_name' => 'Northeast Caucasian',
    'iso_639_6_code' => NULL,
  ),
  'ny' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ny',
    'iso_639_1_name' => 'Chichewa, Chewa, Nyanja',
    'iso_639_1_native' => 'chiCheŵa, chinyanja',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'nya',
    'iso_639_2_b_code' => 'nya',
    'iso_639_3_code' => 'nya',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'zh' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'zh',
    'iso_639_1_name' => 'Chinese',
    'iso_639_1_native' => '中文 (Zhōngwén), 汉语, 漢語',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'zho',
    'iso_639_2_b_code' => 'chi',
    'iso_639_3_code' => 'zho',
    'iso_639_5_code' => 'sit',
    'iso_639_5_name' => 'Sino-Tibetan',
    'iso_639_6_code' => NULL,
  ),
  'cu' => 
  array (
    'macrolanguage' => false,
    'ancient' => true,
    'iso_639_1_code' => 'cu',
    'iso_639_1_name' => 'Church Slavonic, Old Slavonic, Old Church Slavonic',
    'iso_639_1_native' => 'ѩзыкъ словѣньскъ',
    'iso_639_1_notes' => 'In use by the Eastern Orthodox Church',
    'iso_639_2_t_code' => 'chu',
    'iso_639_2_b_code' => 'chu',
    'iso_639_3_code' => 'chu',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'cv' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'cv',
    'iso_639_1_name' => 'Chuvash',
    'iso_639_1_native' => 'чӑваш чӗлхи',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'chv',
    'iso_639_2_b_code' => 'chv',
    'iso_639_3_code' => 'chv',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'kw' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'kw',
    'iso_639_1_name' => 'Cornish',
    'iso_639_1_native' => 'Kernewek',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'cor',
    'iso_639_2_b_code' => 'cor',
    'iso_639_3_code' => 'cor',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'co' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'co',
    'iso_639_1_name' => 'Corsican',
    'iso_639_1_native' => 'corsu, lingua corsa',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'cos',
    'iso_639_2_b_code' => 'cos',
    'iso_639_3_code' => 'cos',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'cr' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'cr',
    'iso_639_1_name' => 'Cree',
    'iso_639_1_native' => 'ᓀᐦᐃᔭᐍᐏᐣ',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'cre',
    'iso_639_2_b_code' => 'cre',
    'iso_639_3_code' => 'cre',
    'iso_639_5_code' => 'alg',
    'iso_639_5_name' => 'Algonquian',
    'iso_639_6_code' => NULL,
  ),
  'hr' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'hr',
    'iso_639_1_name' => 'Croatian',
    'iso_639_1_native' => 'hrvatski jezik',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'hrv',
    'iso_639_2_b_code' => 'hrv',
    'iso_639_3_code' => 'hrv',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'cs' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'cs',
    'iso_639_1_name' => 'Czech',
    'iso_639_1_native' => 'čeština, český jazyk',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'ces',
    'iso_639_2_b_code' => 'cze',
    'iso_639_3_code' => 'ces',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'da' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'da',
    'iso_639_1_name' => 'Danish',
    'iso_639_1_native' => 'dansk',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'dan',
    'iso_639_2_b_code' => 'dan',
    'iso_639_3_code' => 'dan',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'dv' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'dv',
    'iso_639_1_name' => 'Divehi, Dhivehi, Maldivian',
    'iso_639_1_native' => 'ދިވެހި',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'div',
    'iso_639_2_b_code' => 'div',
    'iso_639_3_code' => 'div',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'nl' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'nl',
    'iso_639_1_name' => 'Dutch, Flemish',
    'iso_639_1_native' => 'Nederlands, Vlaams',
    'iso_639_1_notes' => 'Flemish is not to be confused with the closely related West Flemish which is referred to as Vlaams (Dutch for "Flemish") in ISO 639-3 and has the ISO 639-3 code vls',
    'iso_639_2_t_code' => 'nld',
    'iso_639_2_b_code' => 'dut',
    'iso_639_3_code' => 'nld',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'dz' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'dz',
    'iso_639_1_name' => 'Dzongkha',
    'iso_639_1_native' => 'རྫོང་ཁ',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'dzo',
    'iso_639_2_b_code' => 'dzo',
    'iso_639_3_code' => 'dzo',
    'iso_639_5_code' => 'sit',
    'iso_639_5_name' => 'Sino-Tibetan',
    'iso_639_6_code' => NULL,
  ),
  'en' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'en',
    'iso_639_1_name' => 'English',
    'iso_639_1_native' => 'English',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'eng',
    'iso_639_2_b_code' => 'eng',
    'iso_639_3_code' => 'eng',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'engs',
  ),
  'eo' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'eo',
    'iso_639_1_name' => 'Esperanto',
    'iso_639_1_native' => 'Esperanto',
    'iso_639_1_notes' => 'Constructed, initially by L.L. Zamenhof in 1887',
    'iso_639_2_t_code' => 'epo',
    'iso_639_2_b_code' => 'epo',
    'iso_639_3_code' => 'epo',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Constructed',
    'iso_639_6_code' => NULL,
  ),
  'et' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'et',
    'iso_639_1_name' => 'Estonian',
    'iso_639_1_native' => 'eesti, eesti keel',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'est',
    'iso_639_2_b_code' => 'est',
    'iso_639_3_code' => 'est',
    'iso_639_5_code' => 'urj',
    'iso_639_5_name' => 'Uralic',
    'iso_639_6_code' => NULL,
  ),
  'ee' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ee',
    'iso_639_1_name' => 'Ewe',
    'iso_639_1_native' => 'Eʋegbe',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'ewe',
    'iso_639_2_b_code' => 'ewe',
    'iso_639_3_code' => 'ewe',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'fo' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'fo',
    'iso_639_1_name' => 'Faroese',
    'iso_639_1_native' => 'føroyskt',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'fao',
    'iso_639_2_b_code' => 'fao',
    'iso_639_3_code' => 'fao',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'fj' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'fj',
    'iso_639_1_name' => 'Fijian',
    'iso_639_1_native' => 'vosa Vakaviti',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'fij',
    'iso_639_2_b_code' => 'fij',
    'iso_639_3_code' => 'fij',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'fi' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'fi',
    'iso_639_1_name' => 'Finnish',
    'iso_639_1_native' => 'suomi, suomen kieli',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'fin',
    'iso_639_2_b_code' => 'fin',
    'iso_639_3_code' => 'fin',
    'iso_639_5_code' => 'urj',
    'iso_639_5_name' => 'Uralic',
    'iso_639_6_code' => NULL,
  ),
  'fr' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'fr',
    'iso_639_1_name' => 'French',
    'iso_639_1_native' => 'français, langue française',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'fra',
    'iso_639_2_b_code' => 'fre',
    'iso_639_3_code' => 'fra',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'fras',
  ),
  'fy' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'fy',
    'iso_639_1_name' => 'Western Frisian',
    'iso_639_1_native' => 'Frysk',
    'iso_639_1_notes' => 'Also known as Frisian',
    'iso_639_2_t_code' => 'fry',
    'iso_639_2_b_code' => 'fry',
    'iso_639_3_code' => 'fry',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ff' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ff',
    'iso_639_1_name' => 'Fulah',
    'iso_639_1_native' => 'Fulfulde, Pulaar, Pular',
    'iso_639_1_notes' => 'Also known as Fula',
    'iso_639_2_t_code' => 'ful',
    'iso_639_2_b_code' => 'ful',
    'iso_639_3_code' => 'ful',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'gd' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'gd',
    'iso_639_1_name' => 'Gaelic, Scottish Gaelic',
    'iso_639_1_native' => 'Gàidhlig',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'gla',
    'iso_639_2_b_code' => 'gla',
    'iso_639_3_code' => 'gla',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'gl' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'gl',
    'iso_639_1_name' => 'Galician',
    'iso_639_1_native' => 'galego',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'glg',
    'iso_639_2_b_code' => 'glg',
    'iso_639_3_code' => 'glg',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'lg' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'lg',
    'iso_639_1_name' => 'Ganda',
    'iso_639_1_native' => 'Luganda',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'lug',
    'iso_639_2_b_code' => 'lug',
    'iso_639_3_code' => 'lug',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ka' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ka',
    'iso_639_1_name' => 'Georgian',
    'iso_639_1_native' => 'ქართული',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kat',
    'iso_639_2_b_code' => 'geo',
    'iso_639_3_code' => 'kat',
    'iso_639_5_code' => 'ccs',
    'iso_639_5_name' => 'South Caucasian',
    'iso_639_6_code' => NULL,
  ),
  'de' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'de',
    'iso_639_1_name' => 'German',
    'iso_639_1_native' => 'Deutsch',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'deu',
    'iso_639_2_b_code' => 'ger',
    'iso_639_3_code' => 'deu',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'deus',
  ),
  'el' => 
  array (
    'macrolanguage' => false,
    'ancient' => true,
    'iso_639_1_code' => 'el',
    'iso_639_1_name' => 'Greek, Modern (1453–)',
    'iso_639_1_native' => 'ελληνικά',
    'iso_639_1_notes' => 'For Ancient Greek, use the ISO 639-3 code grc',
    'iso_639_2_t_code' => 'ell',
    'iso_639_2_b_code' => 'gre',
    'iso_639_3_code' => 'ell',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'ells',
  ),
  'kl' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'kl',
    'iso_639_1_name' => 'Kalaallisut, Greenlandic',
    'iso_639_1_native' => 'kalaallisut, kalaallit oqaasii',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kal',
    'iso_639_2_b_code' => 'kal',
    'iso_639_3_code' => 'kal',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Eskimo–Aleut',
    'iso_639_6_code' => NULL,
  ),
  'gn' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'gn',
    'iso_639_1_name' => 'Guarani',
    'iso_639_1_native' => 'Avañe\'ẽ',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'grn',
    'iso_639_2_b_code' => 'grn',
    'iso_639_3_code' => 'grn',
    'iso_639_5_code' => 'tup',
    'iso_639_5_name' => 'Tupian',
    'iso_639_6_code' => NULL,
  ),
  'gu' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'gu',
    'iso_639_1_name' => 'Gujarati',
    'iso_639_1_native' => 'ગુજરાતી',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'guj',
    'iso_639_2_b_code' => 'guj',
    'iso_639_3_code' => 'guj',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ht' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ht',
    'iso_639_1_name' => 'Haitian, Haitian Creole',
    'iso_639_1_native' => 'Kreyòl ayisyen',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'hat',
    'iso_639_2_b_code' => 'hat',
    'iso_639_3_code' => 'hat',
    'iso_639_5_code' => 'crp',
    'iso_639_5_name' => 'Creole',
    'iso_639_6_code' => NULL,
  ),
  'ha' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ha',
    'iso_639_1_name' => 'Hausa',
    'iso_639_1_native' => '(Hausa) هَوُسَ',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'hau',
    'iso_639_2_b_code' => 'hau',
    'iso_639_3_code' => 'hau',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => NULL,
  ),
  'he' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'he',
    'iso_639_1_name' => 'Hebrew',
    'iso_639_1_native' => 'עברית',
    'iso_639_1_notes' => 'Modern Hebrew. Code changed in 1989 from original ISO 639:1988, iw',
    'iso_639_2_t_code' => 'heb',
    'iso_639_2_b_code' => 'heb',
    'iso_639_3_code' => 'heb',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => NULL,
  ),
  'hz' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'hz',
    'iso_639_1_name' => 'Herero',
    'iso_639_1_native' => 'Otjiherero',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'her',
    'iso_639_2_b_code' => 'her',
    'iso_639_3_code' => 'her',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'hi' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'hi',
    'iso_639_1_name' => 'Hindi',
    'iso_639_1_native' => 'हिन्दी, हिंदी',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'hin',
    'iso_639_2_b_code' => 'hin',
    'iso_639_3_code' => 'hin',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'hins',
  ),
  'ho' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ho',
    'iso_639_1_name' => 'Hiri Motu',
    'iso_639_1_native' => 'Hiri Motu',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'hmo',
    'iso_639_2_b_code' => 'hmo',
    'iso_639_3_code' => 'hmo',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'hu' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'hu',
    'iso_639_1_name' => 'Hungarian',
    'iso_639_1_native' => 'magyar',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'hun',
    'iso_639_2_b_code' => 'hun',
    'iso_639_3_code' => 'hun',
    'iso_639_5_code' => 'urj',
    'iso_639_5_name' => 'Uralic',
    'iso_639_6_code' => NULL,
  ),
  'is' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'is',
    'iso_639_1_name' => 'Icelandic',
    'iso_639_1_native' => 'Íslenska',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'isl',
    'iso_639_2_b_code' => 'ice',
    'iso_639_3_code' => 'isl',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'io' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'io',
    'iso_639_1_name' => 'Ido',
    'iso_639_1_native' => 'Ido',
    'iso_639_1_notes' => 'Constructed by De Beaufront, 1907, as variation of Esperanto',
    'iso_639_2_t_code' => 'ido',
    'iso_639_2_b_code' => 'ido',
    'iso_639_3_code' => 'ido',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Constructed',
    'iso_639_6_code' => 'idos',
  ),
  'ig' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ig',
    'iso_639_1_name' => 'Igbo',
    'iso_639_1_native' => 'Asụsụ Igbo',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'ibo',
    'iso_639_2_b_code' => 'ibo',
    'iso_639_3_code' => 'ibo',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'id' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'id',
    'iso_639_1_name' => 'Indonesian',
    'iso_639_1_native' => 'Bahasa Indonesia',
    'iso_639_1_notes' => 'Changed in 1989 from original ISO 639:1988. Covered by macrolanguage ms/msa.',
    'iso_639_2_t_code' => 'ind',
    'iso_639_2_b_code' => 'ind',
    'iso_639_3_code' => 'ind',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'ia' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ia',
    'iso_639_1_name' => 'Interlingua (International Auxiliary Language Association)',
    'iso_639_1_native' => 'Interlingua',
    'iso_639_1_notes' => 'Constructed by the International Auxiliary Language Association',
    'iso_639_2_t_code' => 'ina',
    'iso_639_2_b_code' => 'ina',
    'iso_639_3_code' => 'ina',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Constructed',
    'iso_639_6_code' => NULL,
  ),
  'ie' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ie',
    'iso_639_1_name' => 'Interlingue, Occidental',
    'iso_639_1_native' => NULL,
    'iso_639_1_notes' => 'Constructed by Edgar de Wahl, first published in 1922',
    'iso_639_2_t_code' => 'ile',
    'iso_639_2_b_code' => 'ile',
    'iso_639_3_code' => 'ile',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => NULL,
    'iso_639_6_code' => NULL,
  ),
  'iu' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'iu',
    'iso_639_1_name' => 'Inuktitut',
    'iso_639_1_native' => 'ᐃᓄᒃᑎᑐᑦ',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'iku',
    'iso_639_2_b_code' => 'iku',
    'iso_639_3_code' => 'iku',
    'iso_639_5_code' => 'esx',
    'iso_639_5_name' => 'Eskimo–Aleut',
    'iso_639_6_code' => NULL,
  ),
  'ik' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ik',
    'iso_639_1_name' => 'Inupiaq',
    'iso_639_1_native' => 'Iñupiaq, Iñupiatun',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'ipk',
    'iso_639_2_b_code' => 'ipk',
    'iso_639_3_code' => 'ipk',
    'iso_639_5_code' => 'esx',
    'iso_639_5_name' => 'Eskimo–Aleut',
    'iso_639_6_code' => NULL,
  ),
  'ga' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ga',
    'iso_639_1_name' => 'Irish',
    'iso_639_1_native' => 'Gaeilge',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'gle',
    'iso_639_2_b_code' => 'gle',
    'iso_639_3_code' => 'gle',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'it' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'it',
    'iso_639_1_name' => 'Italian',
    'iso_639_1_native' => 'italiano',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'ita',
    'iso_639_2_b_code' => 'ita',
    'iso_639_3_code' => 'ita',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'itas',
  ),
  'ja' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ja',
    'iso_639_1_name' => 'Japanese',
    'iso_639_1_native' => '日本語 (にほんご)',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'jpn',
    'iso_639_2_b_code' => 'jpn',
    'iso_639_3_code' => 'jpn',
    'iso_639_5_code' => 'jpx',
    'iso_639_5_name' => 'Japonic',
    'iso_639_6_code' => NULL,
  ),
  'jv' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'jv',
    'iso_639_1_name' => 'Javanese',
    'iso_639_1_native' => 'basa Jawa',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'jav',
    'iso_639_2_b_code' => 'jav',
    'iso_639_3_code' => 'jav',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'kn' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'kn',
    'iso_639_1_name' => 'Kannada',
    'iso_639_1_native' => 'ಕನ್ನಡ',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kan',
    'iso_639_2_b_code' => 'kan',
    'iso_639_3_code' => 'kan',
    'iso_639_5_code' => 'dra',
    'iso_639_5_name' => 'Dravidian',
    'iso_639_6_code' => NULL,
  ),
  'kr' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'kr',
    'iso_639_1_name' => 'Kanuri',
    'iso_639_1_native' => 'Kanuri',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'kau',
    'iso_639_2_b_code' => 'kau',
    'iso_639_3_code' => 'kau',
    'iso_639_5_code' => 'ssa',
    'iso_639_5_name' => 'Nilo-Saharan',
    'iso_639_6_code' => NULL,
  ),
  'ks' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ks',
    'iso_639_1_name' => 'Kashmiri',
    'iso_639_1_native' => 'कश्मीरी, كشميري',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kas',
    'iso_639_2_b_code' => 'kas',
    'iso_639_3_code' => 'kas',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'kk' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'kk',
    'iso_639_1_name' => 'Kazakh',
    'iso_639_1_native' => 'қазақ тілі',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kaz',
    'iso_639_2_b_code' => 'kaz',
    'iso_639_3_code' => 'kaz',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'km' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'km',
    'iso_639_1_name' => 'Central Khmer',
    'iso_639_1_native' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
    'iso_639_1_notes' => 'Also known as Khmer or Cambodian',
    'iso_639_2_t_code' => 'khm',
    'iso_639_2_b_code' => 'khm',
    'iso_639_3_code' => 'khm',
    'iso_639_5_code' => 'aav',
    'iso_639_5_name' => 'Austroasiatic',
    'iso_639_6_code' => NULL,
  ),
  'ki' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ki',
    'iso_639_1_name' => 'Kikuyu, Gikuyu',
    'iso_639_1_native' => 'Gĩkũyũ',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kik',
    'iso_639_2_b_code' => 'kik',
    'iso_639_3_code' => 'kik',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'rw' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'rw',
    'iso_639_1_name' => 'Kinyarwanda',
    'iso_639_1_native' => 'Ikinyarwanda',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kin',
    'iso_639_2_b_code' => 'kin',
    'iso_639_3_code' => 'kin',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ky' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ky',
    'iso_639_1_name' => 'Kirghiz, Kyrgyz',
    'iso_639_1_native' => 'Кыргызча, Кыргыз тили',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kir',
    'iso_639_2_b_code' => 'kir',
    'iso_639_3_code' => 'kir',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'kv' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'kv',
    'iso_639_1_name' => 'Komi',
    'iso_639_1_native' => 'коми кыв',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'kom',
    'iso_639_2_b_code' => 'kom',
    'iso_639_3_code' => 'kom',
    'iso_639_5_code' => 'urj',
    'iso_639_5_name' => 'Uralic',
    'iso_639_6_code' => NULL,
  ),
  'kg' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'kg',
    'iso_639_1_name' => 'Kongo',
    'iso_639_1_native' => 'Kikongo',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'kon',
    'iso_639_2_b_code' => 'kon',
    'iso_639_3_code' => 'kon',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ko' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ko',
    'iso_639_1_name' => 'Korean',
    'iso_639_1_native' => '한국어, 조선어',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kor',
    'iso_639_2_b_code' => 'kor',
    'iso_639_3_code' => 'kor',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Koreanic',
    'iso_639_6_code' => NULL,
  ),
  'kj' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'kj',
    'iso_639_1_name' => 'Kuanyama, Kwanyama',
    'iso_639_1_native' => 'Kuanyama',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'kua',
    'iso_639_2_b_code' => 'kua',
    'iso_639_3_code' => 'kua',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ku' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ku',
    'iso_639_1_name' => 'Kurdish',
    'iso_639_1_native' => 'Kurdî, كوردی',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'kur',
    'iso_639_2_b_code' => 'kur',
    'iso_639_3_code' => 'kur',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'lo' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'lo',
    'iso_639_1_name' => 'Lao',
    'iso_639_1_native' => 'ພາສາລາວ',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'lao',
    'iso_639_2_b_code' => 'lao',
    'iso_639_3_code' => 'lao',
    'iso_639_5_code' => 'tai',
    'iso_639_5_name' => 'Tai–Kadai',
    'iso_639_6_code' => NULL,
  ),
  'la' => 
  array (
    'macrolanguage' => false,
    'ancient' => true,
    'iso_639_1_code' => 'la',
    'iso_639_1_name' => 'Latin',
    'iso_639_1_native' => 'latine, lingua latina',
    'iso_639_1_notes' => 'ancient',
    'iso_639_2_t_code' => 'lat',
    'iso_639_2_b_code' => 'lat',
    'iso_639_3_code' => 'lat',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'lats',
  ),
  'lv' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'lv',
    'iso_639_1_name' => 'Latvian',
    'iso_639_1_native' => 'latviešu valoda',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'lav',
    'iso_639_2_b_code' => 'lav',
    'iso_639_3_code' => 'lav',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'li' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'li',
    'iso_639_1_name' => 'Limburgan, Limburger, Limburgish',
    'iso_639_1_native' => 'Limburgs',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'lim',
    'iso_639_2_b_code' => 'lim',
    'iso_639_3_code' => 'lim',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ln' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ln',
    'iso_639_1_name' => 'Lingala',
    'iso_639_1_native' => 'Lingála',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'lin',
    'iso_639_2_b_code' => 'lin',
    'iso_639_3_code' => 'lin',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'lt' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'lt',
    'iso_639_1_name' => 'Lithuanian',
    'iso_639_1_native' => 'lietuvių kalba',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'lit',
    'iso_639_2_b_code' => 'lit',
    'iso_639_3_code' => 'lit',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'lu' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'lu',
    'iso_639_1_name' => 'Luba-Katanga',
    'iso_639_1_native' => 'Tshiluba',
    'iso_639_1_notes' => 'Also known as Luba-Shaba',
    'iso_639_2_t_code' => 'lub',
    'iso_639_2_b_code' => 'lub',
    'iso_639_3_code' => 'lub',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'lb' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'lb',
    'iso_639_1_name' => 'Luxembourgish, Letzeburgesch',
    'iso_639_1_native' => 'Lëtzebuergesch',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'ltz',
    'iso_639_2_b_code' => 'ltz',
    'iso_639_3_code' => 'ltz',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'mk' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'mk',
    'iso_639_1_name' => 'Macedonian',
    'iso_639_1_native' => 'македонски јазик',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'mkd',
    'iso_639_2_b_code' => 'mac',
    'iso_639_3_code' => 'mkd',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'mg' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'mg',
    'iso_639_1_name' => 'Malagasy',
    'iso_639_1_native' => 'fiteny malagasy',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'mlg',
    'iso_639_2_b_code' => 'mlg',
    'iso_639_3_code' => 'mlg',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'ms' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ms',
    'iso_639_1_name' => 'Malay',
    'iso_639_1_native' => 'bahasa Melayu, بهاس ملايو',
    'iso_639_1_notes' => 'Standard Malay is zsm, Indonesian is id/ind',
    'iso_639_2_t_code' => 'msa',
    'iso_639_2_b_code' => 'may',
    'iso_639_3_code' => 'msa',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'ml' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ml',
    'iso_639_1_name' => 'Malayalam',
    'iso_639_1_native' => 'മലയാളം',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'mal',
    'iso_639_2_b_code' => 'mal',
    'iso_639_3_code' => 'mal',
    'iso_639_5_code' => 'dra',
    'iso_639_5_name' => 'Dravidian',
    'iso_639_6_code' => NULL,
  ),
  'mt' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'mt',
    'iso_639_1_name' => 'Maltese',
    'iso_639_1_native' => 'Malti',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'mlt',
    'iso_639_2_b_code' => 'mlt',
    'iso_639_3_code' => 'mlt',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => NULL,
  ),
  'gv' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'gv',
    'iso_639_1_name' => 'Manx',
    'iso_639_1_native' => 'Gaelg, Gailck',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'glv',
    'iso_639_2_b_code' => 'glv',
    'iso_639_3_code' => 'glv',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'mi' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'mi',
    'iso_639_1_name' => 'Maori',
    'iso_639_1_native' => 'te reo Māori',
    'iso_639_1_notes' => 'Also known as Māori',
    'iso_639_2_t_code' => 'mri',
    'iso_639_2_b_code' => 'mao',
    'iso_639_3_code' => 'mri',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'mr' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'mr',
    'iso_639_1_name' => 'Marathi',
    'iso_639_1_native' => 'मराठी',
    'iso_639_1_notes' => 'Also known as Marāṭhī',
    'iso_639_2_t_code' => 'mar',
    'iso_639_2_b_code' => 'mar',
    'iso_639_3_code' => 'mar',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'mh' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'mh',
    'iso_639_1_name' => 'Marshallese',
    'iso_639_1_native' => 'Kajin M̧ajeļ',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'mah',
    'iso_639_2_b_code' => 'mah',
    'iso_639_3_code' => 'mah',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'mn' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'mn',
    'iso_639_1_name' => 'Mongolian',
    'iso_639_1_native' => 'монгол',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'mon',
    'iso_639_2_b_code' => 'mon',
    'iso_639_3_code' => 'mon',
    'iso_639_5_code' => 'xgn',
    'iso_639_5_name' => 'Mongolic',
    'iso_639_6_code' => NULL,
  ),
  'na' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'na',
    'iso_639_1_name' => 'Nauru',
    'iso_639_1_native' => 'Ekakairũ Naoero',
    'iso_639_1_notes' => 'Also known as Nauruan',
    'iso_639_2_t_code' => 'nau',
    'iso_639_2_b_code' => 'nau',
    'iso_639_3_code' => 'nau',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'nv' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'nv',
    'iso_639_1_name' => 'Navajo, Navaho',
    'iso_639_1_native' => 'Diné bizaad',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'nav',
    'iso_639_2_b_code' => 'nav',
    'iso_639_3_code' => 'nav',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Dené–Yeniseian',
    'iso_639_6_code' => NULL,
  ),
  'nd' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'nd',
    'iso_639_1_name' => 'North Ndebele',
    'iso_639_1_native' => 'isiNdebele',
    'iso_639_1_notes' => 'Also known as Northern Ndebele',
    'iso_639_2_t_code' => 'nde',
    'iso_639_2_b_code' => 'nde',
    'iso_639_3_code' => 'nde',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'nr' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'nr',
    'iso_639_1_name' => 'South Ndebele',
    'iso_639_1_native' => 'isiNdebele',
    'iso_639_1_notes' => 'Also known as Southern Ndebele',
    'iso_639_2_t_code' => 'nbl',
    'iso_639_2_b_code' => 'nbl',
    'iso_639_3_code' => 'nbl',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ng' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ng',
    'iso_639_1_name' => 'Ndonga',
    'iso_639_1_native' => 'Owambo',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'ndo',
    'iso_639_2_b_code' => 'ndo',
    'iso_639_3_code' => 'ndo',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ne' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ne',
    'iso_639_1_name' => 'Nepali',
    'iso_639_1_native' => 'नेपाली',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'nep',
    'iso_639_2_b_code' => 'nep',
    'iso_639_3_code' => 'nep',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'no' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'no',
    'iso_639_1_name' => 'Norwegian',
    'iso_639_1_native' => 'Norsk',
    'iso_639_1_notes' => 'Bokmål is nb/nob, Nynorsk is nn/nno',
    'iso_639_2_t_code' => 'nor',
    'iso_639_2_b_code' => 'nor',
    'iso_639_3_code' => 'nor',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'nb' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'nb',
    'iso_639_1_name' => 'Norwegian Bokmål',
    'iso_639_1_native' => 'Norsk bokmål',
    'iso_639_1_notes' => 'Covered by macrolanguage no/nor',
    'iso_639_2_t_code' => 'nob',
    'iso_639_2_b_code' => 'nob',
    'iso_639_3_code' => 'nob',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'nn' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'nn',
    'iso_639_1_name' => 'Norwegian Nynorsk',
    'iso_639_1_native' => 'Norsk nynorsk',
    'iso_639_1_notes' => 'Covered by macrolanguage no/nor',
    'iso_639_2_t_code' => 'nno',
    'iso_639_2_b_code' => 'nno',
    'iso_639_3_code' => 'nno',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ii' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ii',
    'iso_639_1_name' => 'Sichuan Yi, Nuosu',
    'iso_639_1_native' => 'ꆈꌠ꒿ Nuosuhxop',
    'iso_639_1_notes' => 'Standard form of the Yi languages',
    'iso_639_2_t_code' => 'iii',
    'iso_639_2_b_code' => 'iii',
    'iso_639_3_code' => 'iii',
    'iso_639_5_code' => 'sit',
    'iso_639_5_name' => 'Sino-Tibetan',
    'iso_639_6_code' => NULL,
  ),
  'oc' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'oc',
    'iso_639_1_name' => 'Occitan',
    'iso_639_1_native' => 'occitan, lenga d\'òc',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'oci',
    'iso_639_2_b_code' => 'oci',
    'iso_639_3_code' => 'oci',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'oj' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'oj',
    'iso_639_1_name' => 'Ojibwa',
    'iso_639_1_native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
    'iso_639_1_notes' => 'Also known as Ojibwe',
    'iso_639_2_t_code' => 'oji',
    'iso_639_2_b_code' => 'oji',
    'iso_639_3_code' => 'oji',
    'iso_639_5_code' => 'alg',
    'iso_639_5_name' => 'Algonquian',
    'iso_639_6_code' => NULL,
  ),
  'or' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'or',
    'iso_639_1_name' => 'Oriya',
    'iso_639_1_native' => 'ଓଡ଼ିଆ',
    'iso_639_1_notes' => 'Also known as Odia',
    'iso_639_2_t_code' => 'ori',
    'iso_639_2_b_code' => 'ori',
    'iso_639_3_code' => 'ori',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'om' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'om',
    'iso_639_1_name' => 'Oromo',
    'iso_639_1_native' => 'Afaan Oromoo',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'orm',
    'iso_639_2_b_code' => 'orm',
    'iso_639_3_code' => 'orm',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => NULL,
  ),
  'os' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'os',
    'iso_639_1_name' => 'Ossetian, Ossetic',
    'iso_639_1_native' => 'ирон æвзаг',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'oss',
    'iso_639_2_b_code' => 'oss',
    'iso_639_3_code' => 'oss',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'pi' => 
  array (
    'macrolanguage' => false,
    'ancient' => true,
    'iso_639_1_code' => 'pi',
    'iso_639_1_name' => 'Pali',
    'iso_639_1_native' => 'पाऴि',
    'iso_639_1_notes' => 'Also known as Pāli',
    'iso_639_2_t_code' => 'pli',
    'iso_639_2_b_code' => 'pli',
    'iso_639_3_code' => 'pli',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ps' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'ps',
    'iso_639_1_name' => 'Pashto, Pushto',
    'iso_639_1_native' => 'پښتو',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'pus',
    'iso_639_2_b_code' => 'pus',
    'iso_639_3_code' => 'pus',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'fa' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'fa',
    'iso_639_1_name' => 'Persian',
    'iso_639_1_native' => 'فارسی',
    'iso_639_1_notes' => 'Also known as Farsi',
    'iso_639_2_t_code' => 'fas',
    'iso_639_2_b_code' => 'per',
    'iso_639_3_code' => 'fas',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'pl' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'pl',
    'iso_639_1_name' => 'Polish',
    'iso_639_1_native' => 'język polski, polszczyzna',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'pol',
    'iso_639_2_b_code' => 'pol',
    'iso_639_3_code' => 'pol',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => 'pols',
  ),
  'pt' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'pt',
    'iso_639_1_name' => 'Portuguese',
    'iso_639_1_native' => 'português',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'por',
    'iso_639_2_b_code' => 'por',
    'iso_639_3_code' => 'por',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'pa' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'pa',
    'iso_639_1_name' => 'Punjabi, Panjabi',
    'iso_639_1_native' => 'ਪੰਜਾਬੀ, پنجابی',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'pan',
    'iso_639_2_b_code' => 'pan',
    'iso_639_3_code' => 'pan',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'qu' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'qu',
    'iso_639_1_name' => 'Quechua',
    'iso_639_1_native' => 'Runa Simi, Kichwa',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'que',
    'iso_639_2_b_code' => 'que',
    'iso_639_3_code' => 'que',
    'iso_639_5_code' => 'qwe',
    'iso_639_5_name' => 'Quechuan',
    'iso_639_6_code' => NULL,
  ),
  'ro' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ro',
    'iso_639_1_name' => 'Romanian, Moldavian, Moldovan',
    'iso_639_1_native' => 'limba română',
    'iso_639_1_notes' => 'The identifiers mo and mol for Moldavian are deprecated. They will not be assigned to different items, and recordings using these identifiers will not be invalid',
    'iso_639_2_t_code' => 'ron',
    'iso_639_2_b_code' => 'rum',
    'iso_639_3_code' => 'ron',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'rm' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'rm',
    'iso_639_1_name' => 'Romansh',
    'iso_639_1_native' => 'rumantsch grischun',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'roh',
    'iso_639_2_b_code' => 'roh',
    'iso_639_3_code' => 'roh',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'rn' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'rn',
    'iso_639_1_name' => 'Rundi',
    'iso_639_1_native' => 'Ikirundi',
    'iso_639_1_notes' => 'Also known as Kirundi',
    'iso_639_2_t_code' => 'run',
    'iso_639_2_b_code' => 'run',
    'iso_639_3_code' => 'run',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ru' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ru',
    'iso_639_1_name' => 'Russian',
    'iso_639_1_native' => 'Русский',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'rus',
    'iso_639_2_b_code' => 'rus',
    'iso_639_3_code' => 'rus',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'se' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'se',
    'iso_639_1_name' => 'Northern Sami',
    'iso_639_1_native' => 'Davvisámegiella',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'sme',
    'iso_639_2_b_code' => 'sme',
    'iso_639_3_code' => 'sme',
    'iso_639_5_code' => 'urj',
    'iso_639_5_name' => 'Uralic',
    'iso_639_6_code' => NULL,
  ),
  'sm' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'sm',
    'iso_639_1_name' => 'Samoan',
    'iso_639_1_native' => 'gagana fa\'a Samoa',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'smo',
    'iso_639_2_b_code' => 'smo',
    'iso_639_3_code' => 'smo',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'sg' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'sg',
    'iso_639_1_name' => 'Sango',
    'iso_639_1_native' => 'yângâ tî sängö',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'sag',
    'iso_639_2_b_code' => 'sag',
    'iso_639_3_code' => 'sag',
    'iso_639_5_code' => 'crp',
    'iso_639_5_name' => 'Creole',
    'iso_639_6_code' => NULL,
  ),
  'sa' => 
  array (
    'macrolanguage' => false,
    'ancient' => true,
    'iso_639_1_code' => 'sa',
    'iso_639_1_name' => 'Sanskrit',
    'iso_639_1_native' => 'संस्कृतम्',
    'iso_639_1_notes' => 'ancient, still spoken',
    'iso_639_2_t_code' => 'san',
    'iso_639_2_b_code' => 'san',
    'iso_639_3_code' => 'san',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'sc' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'sc',
    'iso_639_1_name' => 'Sardinian',
    'iso_639_1_native' => 'sardu',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'srd',
    'iso_639_2_b_code' => 'srd',
    'iso_639_3_code' => 'srd',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'sr' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'sr',
    'iso_639_1_name' => 'Serbian',
    'iso_639_1_native' => 'српски језик',
    'iso_639_1_notes' => 'The ISO 639-2/T code srp deprecated the ISO 639-2/B code scc',
    'iso_639_2_t_code' => 'srp',
    'iso_639_2_b_code' => 'srp',
    'iso_639_3_code' => 'srp',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'sn' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'sn',
    'iso_639_1_name' => 'Shona',
    'iso_639_1_native' => 'chiShona',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'sna',
    'iso_639_2_b_code' => 'sna',
    'iso_639_3_code' => 'sna',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'sd' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'sd',
    'iso_639_1_name' => 'Sindhi',
    'iso_639_1_native' => 'सिन्धी, سنڌي، سندھی',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'snd',
    'iso_639_2_b_code' => 'snd',
    'iso_639_3_code' => 'snd',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'si' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'si',
    'iso_639_1_name' => 'Sinhala, Sinhalese',
    'iso_639_1_native' => 'සිංහල',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'sin',
    'iso_639_2_b_code' => 'sin',
    'iso_639_3_code' => 'sin',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'sk' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'sk',
    'iso_639_1_name' => 'Slovak',
    'iso_639_1_native' => 'slovenčina, slovenský jazyk',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'slk',
    'iso_639_2_b_code' => 'slo',
    'iso_639_3_code' => 'slk',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'sl' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'sl',
    'iso_639_1_name' => 'Slovenian',
    'iso_639_1_native' => 'slovenski jezik, slovenščina',
    'iso_639_1_notes' => 'Also known as Slovene',
    'iso_639_2_t_code' => 'slv',
    'iso_639_2_b_code' => 'slv',
    'iso_639_3_code' => 'slv',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'so' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'so',
    'iso_639_1_name' => 'Somali',
    'iso_639_1_native' => 'Soomaaliga, af Soomaali',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'som',
    'iso_639_2_b_code' => 'som',
    'iso_639_3_code' => 'som',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => NULL,
  ),
  'st' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'st',
    'iso_639_1_name' => 'Southern Sotho',
    'iso_639_1_native' => 'Sesotho',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'sot',
    'iso_639_2_b_code' => 'sot',
    'iso_639_3_code' => 'sot',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'es' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'es',
    'iso_639_1_name' => 'Spanish, Castilian',
    'iso_639_1_native' => 'español',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'spa',
    'iso_639_2_b_code' => 'spa',
    'iso_639_3_code' => 'spa',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'su' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'su',
    'iso_639_1_name' => 'Sundanese',
    'iso_639_1_native' => 'Basa Sunda',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'sun',
    'iso_639_2_b_code' => 'sun',
    'iso_639_3_code' => 'sun',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'sw' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'sw',
    'iso_639_1_name' => 'Swahili',
    'iso_639_1_native' => 'Kiswahili',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'swa',
    'iso_639_2_b_code' => 'swa',
    'iso_639_3_code' => 'swa',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ss' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ss',
    'iso_639_1_name' => 'Swati',
    'iso_639_1_native' => 'SiSwati',
    'iso_639_1_notes' => 'Also known as Swazi',
    'iso_639_2_t_code' => 'ssw',
    'iso_639_2_b_code' => 'ssw',
    'iso_639_3_code' => 'ssw',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'sv' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'sv',
    'iso_639_1_name' => 'Swedish',
    'iso_639_1_native' => 'svenska',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'swe',
    'iso_639_2_b_code' => 'swe',
    'iso_639_3_code' => 'swe',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'tl' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'tl',
    'iso_639_1_name' => 'Tagalog',
    'iso_639_1_native' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
    'iso_639_1_notes' => 'Filipino (Pilipino) has the code fil',
    'iso_639_2_t_code' => 'tgl',
    'iso_639_2_b_code' => 'tgl',
    'iso_639_3_code' => 'tgl',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'ty' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ty',
    'iso_639_1_name' => 'Tahitian',
    'iso_639_1_native' => 'Reo Tahiti',
    'iso_639_1_notes' => 'One of the Reo Mā`ohi (languages of French Polynesia)',
    'iso_639_2_t_code' => 'tah',
    'iso_639_2_b_code' => 'tah',
    'iso_639_3_code' => 'tah',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'tg' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'tg',
    'iso_639_1_name' => 'Tajik',
    'iso_639_1_native' => 'тоҷикӣ, toçikī, تاجیکی',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tgk',
    'iso_639_2_b_code' => 'tgk',
    'iso_639_3_code' => 'tgk',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ta' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ta',
    'iso_639_1_name' => 'Tamil',
    'iso_639_1_native' => 'தமிழ்',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tam',
    'iso_639_2_b_code' => 'tam',
    'iso_639_3_code' => 'tam',
    'iso_639_5_code' => 'dra',
    'iso_639_5_name' => 'Dravidian',
    'iso_639_6_code' => NULL,
  ),
  'tt' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'tt',
    'iso_639_1_name' => 'Tatar',
    'iso_639_1_native' => 'татар теле, tatar tele',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tat',
    'iso_639_2_b_code' => 'tat',
    'iso_639_3_code' => 'tat',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'te' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'te',
    'iso_639_1_name' => 'Telugu',
    'iso_639_1_native' => 'తెలుగు',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tel',
    'iso_639_2_b_code' => 'tel',
    'iso_639_3_code' => 'tel',
    'iso_639_5_code' => 'dra',
    'iso_639_5_name' => 'Dravidian',
    'iso_639_6_code' => NULL,
  ),
  'th' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'th',
    'iso_639_1_name' => 'Thai',
    'iso_639_1_native' => 'Originally called Occidental',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tha',
    'iso_639_2_b_code' => 'tha',
    'iso_639_3_code' => 'tha',
    'iso_639_5_code' => 'tai',
    'iso_639_5_name' => 'Constructed',
    'iso_639_6_code' => 'ile',
  ),
  'bo' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'bo',
    'iso_639_1_name' => 'Tibetan',
    'iso_639_1_native' => 'བོད་ཡིག',
    'iso_639_1_notes' => 'Also known as Standard Tibetan',
    'iso_639_2_t_code' => 'bod',
    'iso_639_2_b_code' => 'tib',
    'iso_639_3_code' => 'bod',
    'iso_639_5_code' => 'sit',
    'iso_639_5_name' => 'Sino-Tibetan',
    'iso_639_6_code' => NULL,
  ),
  'ti' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ti',
    'iso_639_1_name' => 'Tigrinya',
    'iso_639_1_native' => 'ትግርኛ',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tir',
    'iso_639_2_b_code' => 'tir',
    'iso_639_3_code' => 'tir',
    'iso_639_5_code' => 'afa',
    'iso_639_5_name' => 'Afro-Asiatic',
    'iso_639_6_code' => NULL,
  ),
  'to' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'to',
    'iso_639_1_name' => 'Tonga (Tonga Islands)',
    'iso_639_1_native' => 'faka Tonga',
    'iso_639_1_notes' => 'Also known as Tongan',
    'iso_639_2_t_code' => 'ton',
    'iso_639_2_b_code' => 'ton',
    'iso_639_3_code' => 'ton',
    'iso_639_5_code' => 'map',
    'iso_639_5_name' => 'Austronesian',
    'iso_639_6_code' => NULL,
  ),
  'ts' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ts',
    'iso_639_1_name' => 'Tsonga',
    'iso_639_1_native' => 'Xitsonga',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tso',
    'iso_639_2_b_code' => 'tso',
    'iso_639_3_code' => 'tso',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'tn' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'tn',
    'iso_639_1_name' => 'Tswana',
    'iso_639_1_native' => 'Setswana',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tsn',
    'iso_639_2_b_code' => 'tsn',
    'iso_639_3_code' => 'tsn',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'tr' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'tr',
    'iso_639_1_name' => 'Turkish',
    'iso_639_1_native' => 'Türkçe',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tur',
    'iso_639_2_b_code' => 'tur',
    'iso_639_3_code' => 'tur',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'tk' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'tk',
    'iso_639_1_name' => 'Turkmen',
    'iso_639_1_native' => 'Türkmen, Түркмен',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'tuk',
    'iso_639_2_b_code' => 'tuk',
    'iso_639_3_code' => 'tuk',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'tw' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'tw',
    'iso_639_1_name' => 'Twi',
    'iso_639_1_native' => 'Twi',
    'iso_639_1_notes' => 'Covered by macrolanguage ak/aka',
    'iso_639_2_t_code' => 'twi',
    'iso_639_2_b_code' => 'twi',
    'iso_639_3_code' => 'twi',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'ug' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ug',
    'iso_639_1_name' => 'Uighur, Uyghur',
    'iso_639_1_native' => 'ئۇيغۇر تىلى, Уйғур тили, Uyghur tili, Uyƣur tili, Uyğur tili',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'uig',
    'iso_639_2_b_code' => 'uig',
    'iso_639_3_code' => 'uig',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  'uk' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'uk',
    'iso_639_1_name' => 'Ukrainian',
    'iso_639_1_native' => 'українська мова',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'ukr',
    'iso_639_2_b_code' => 'ukr',
    'iso_639_3_code' => 'ukr',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'ur' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'ur',
    'iso_639_1_name' => 'Urdu',
    'iso_639_1_native' => 'اردو',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'urd',
    'iso_639_2_b_code' => 'urd',
    'iso_639_3_code' => 'urd',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'uz' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'uz',
    'iso_639_1_name' => 'Uzbek',
    'iso_639_1_native' => 'Oʻzbekcha, oʻzbek tili, Ўзбекча, ўзбек тили, اۉزبېکچه, اۉزبېک تیلی',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'uzb',
    'iso_639_2_b_code' => 'uzb',
    'iso_639_3_code' => 'uzb',
    'iso_639_5_code' => 'trk',
    'iso_639_5_name' => 'Turkic',
    'iso_639_6_code' => NULL,
  ),
  've' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 've',
    'iso_639_1_name' => 'Venda',
    'iso_639_1_native' => 'Tshivenḓa',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'ven',
    'iso_639_2_b_code' => 'ven',
    'iso_639_3_code' => 'ven',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'vi' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'vi',
    'iso_639_1_name' => 'Vietnamese',
    'iso_639_1_native' => 'Việt Nam',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'vie',
    'iso_639_2_b_code' => 'vie',
    'iso_639_3_code' => 'vie',
    'iso_639_5_code' => 'aav',
    'iso_639_5_name' => 'Austroasiatic',
    'iso_639_6_code' => NULL,
  ),
  'vo' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'vo',
    'iso_639_1_name' => 'Volapük',
    'iso_639_1_native' => 'Volapük',
    'iso_639_1_notes' => 'Constructed',
    'iso_639_2_t_code' => 'vol',
    'iso_639_2_b_code' => 'vol',
    'iso_639_3_code' => 'vol',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Constructed',
    'iso_639_6_code' => NULL,
  ),
  'wa' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'wa',
    'iso_639_1_name' => 'Walloon',
    'iso_639_1_native' => 'walon',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'wln',
    'iso_639_2_b_code' => 'wln',
    'iso_639_3_code' => 'wln',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'cy' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'cy',
    'iso_639_1_name' => 'Welsh',
    'iso_639_1_native' => 'Cymraeg',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'cym',
    'iso_639_2_b_code' => 'wel',
    'iso_639_3_code' => 'cym',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'wo' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'wo',
    'iso_639_1_name' => 'Wolof',
    'iso_639_1_native' => 'Wollof',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'wol',
    'iso_639_2_b_code' => 'wol',
    'iso_639_3_code' => 'wol',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'xh' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'xh',
    'iso_639_1_name' => 'Xhosa',
    'iso_639_1_native' => 'isiXhosa',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'xho',
    'iso_639_2_b_code' => 'xho',
    'iso_639_3_code' => 'xho',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'yi' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'yi',
    'iso_639_1_name' => 'Yiddish',
    'iso_639_1_native' => 'ייִדיש',
    'iso_639_1_notes' => 'Changed in 1989 from original ISO 639:1988, ji',
    'iso_639_2_t_code' => 'yid',
    'iso_639_2_b_code' => 'yid',
    'iso_639_3_code' => 'yid',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  'yo' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'yo',
    'iso_639_1_name' => 'Yoruba',
    'iso_639_1_native' => 'Yorùbá',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'yor',
    'iso_639_2_b_code' => 'yor',
    'iso_639_3_code' => 'yor',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'za' => 
  array (
    'macrolanguage' => true,
    'ancient' => false,
    'iso_639_1_code' => 'za',
    'iso_639_1_name' => 'Zhuang, Chuang',
    'iso_639_1_native' => 'Saɯ cueŋƅ, Saw cuengh',
    'iso_639_1_notes' => 'macrolanguage',
    'iso_639_2_t_code' => 'zha',
    'iso_639_2_b_code' => 'zha',
    'iso_639_3_code' => 'zha',
    'iso_639_5_code' => 'tai',
    'iso_639_5_name' => 'Tai–Kadai',
    'iso_639_6_code' => NULL,
  ),
  'zu' => 
  array (
    'macrolanguage' => false,
    'ancient' => false,
    'iso_639_1_code' => 'zu',
    'iso_639_1_name' => 'Zulu',
    'iso_639_1_native' => 'isiZulu',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => 'zul',
    'iso_639_2_b_code' => 'zul',
    'iso_639_3_code' => 'zul',
    'iso_639_5_code' => NULL,
    'iso_639_5_name' => 'Niger–Congo',
    'iso_639_6_code' => NULL,
  ),
  'bh' => 
  array (
    'iso_639_1_code' => 'bh',
    'iso_639_1_name' => 'Bihari',
    'iso_639_1_native' => 'भोजपुरी',
    'iso_639_1_notes' => 'Collective language code for Bhojpuri, Magahi, and Maithili',
    'iso_639_2_t_code' => 'bih',
    'iso_639_2_b_code' => 'bih',
    'iso_639_3_code' => NULL,
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
  '' => 
  array (
    'iso_639_1_code' => NULL,
    'iso_639_1_name' => 'Ladin',
    'iso_639_1_native' => 'ladin, lingua ladina',
    'iso_639_1_notes' => NULL,
    'iso_639_2_t_code' => NULL,
    'iso_639_2_b_code' => NULL,
    'iso_639_3_code' => 'lld',
    'iso_639_5_code' => 'ine',
    'iso_639_5_name' => 'Indo-European',
    'iso_639_6_code' => NULL,
  ),
);